### ISSUE TITLE
Not able to install the package

### ISSUE THREAD

**Issue by flegarrec** [Mastercard/oauth1-signer-ruby#11] opened 2020-02-10 14:46 UTC
Hello, performed a fresh install of Ruby. Then, directly typed : gem install mastercard_oauth1_signer.gem

I got following response:
ERROR:   While executing gem … (ArgumentError)
“password” is not octal string

I cannot move forward

**Comment by jaaufauvre** [comment] 2020-02-11 12:20
Hi @flegarrec, I can't reproduce this error:

```
PS > choco install ruby
Chocolatey v0.10.15
Installing the following packages: ruby
Progress: Downloading ruby 2.7.0.1... 100%
Ruby is going to be installed in 'C:\tools\ruby27'
Installing 64-bit ruby...
ruby has been installed.
```

```
PS > gem install mastercard_oauth1_signer
Fetching: mastercard_oauth1_signer-1.1.0.gem (100%)
Successfully installed mastercard_oauth1_signer-1.1.0
Parsing documentation for mastercard_oauth1_signer-1.1.0
Installing ri documentation for mastercard_oauth1_signer-1.1.0
Done installing documentation for mastercard_oauth1_signer after 0 seconds
1 gem installed
```

Can you please give more information about your environment (OS, Ruby version, ...)?
Thanks,

**Comment by flegarrec** [comment] 2020-02-11 14:51
Sure, thanks for coming back.
I installed Ruby from this:
https://rubyinstaller.org/downloads/
and selected this for my win 10 x64 install:

WITHOUT DEVKIT

  *   Ruby 2.7.0-1 (x64)<https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.7.0-1/rubyinstaller-2.7.0-1-x64.exe>

From there, opened a command line and a plain 'gem install mastercard_oauth1_signer'
Failed with the 'password is not octal' msg.

________________________________
De : Jean-Alexis Aufauvre <notifications@github.com>
Envoyé : mardi 11 février 2020 13:20
À : Mastercard/oauth1-signer-ruby <oauth1-signer-ruby@noreply.github.com>
Cc : Fred <frederic.legarrec@outlook.com>; Mention <mention@noreply.github.com>
Objet : Re: [Mastercard/oauth1-signer-ruby] Not able to install the package (#11)


Hi @flegarrec<https://github.com/flegarrec>, I can't reproduce this error:

PS > choco install ruby
Chocolatey v0.10.15
Installing the following packages: ruby
Progress: Downloading ruby 2.7.0.1... 100%
Ruby is going to be installed in 'C:\tools\ruby27'
Installing 64-bit ruby...
ruby has been installed.


PS > gem install mastercard_oauth1_signer
Fetching: mastercard_oauth1_signer-1.1.0.gem (100%)
Successfully installed mastercard_oauth1_signer-1.1.0
Parsing documentation for mastercard_oauth1_signer-1.1.0
Installing ri documentation for mastercard_oauth1_signer-1.1.0
Done installing documentation for mastercard_oauth1_signer after 0 seconds
1 gem installed


Can you please give more information about your environment (OS, Ruby version, ...)?
Thanks,

**Comment by jaaufauvre** [comment] 2020-02-11 15:54
Thanks for the details!

An idea: maybe `mastercard_oauth1_signer.gem` couldn't be downloaded or was corrupted (for instance, if you are behind a company proxy).

Can you run `gem install mastercard_oauth1_signer --backtrace --debug`, and then check in your`cache` folder the checksum of `mastercard_oauth1_signer.gem`?

![image](https://user-images.githubusercontent.com/3964455/74252829-1bc05500-4ce6-11ea-874c-b6849ac2cb49.png)

The expected [SHA-256 digest](https://emn178.github.io/online-tools/sha256_checksum.html) is `3a8c6d6185b911b29cf04f9786e0853d6846362ad85f672df11cc8a641ab5164`

https://rubygems.org/gems/mastercard_oauth1_signer/versions/1.1.0

**Comment by jaaufauvre** [comment] 2020-03-20 16:42
Hi @flegarrec, I wanted to check with you if we could close this one?

**Comment by flegarrec** [comment] 2020-03-21 13:32
yes you can. thx

Sent via the Samsung Galaxy S8, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Closed as completed** 2020-03-21 14:21 UTC
Labels: question
